version: '3'
services:

  build:
    image: backend
    command: python manage.py migrate --no-input
    depends_on:
      - postgres_docker_db

  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "8000:8000"
    command: python manage.py runserver
    depends_on:
      - postgres_docker_db
      - build

  postgres_docker_db:
    container_name: postgres_container
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-terradata}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-terradata_default_password$}
      POSTGRES_DB: ${POSTGRES_DB:-terradata}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    restart: unless-stopped

volumes:
    postgres: