# Generated by Django 4.1.5 on 2023-10-30 06:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoprocess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='license',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='resolution',
        ),
        migrations.AddField(
            model_name='layer',
            name='bbox',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='layer',
            name='type_layer',
            field=models.CharField(default='Raster', max_length=100),
        ),
    ]
